### ISSUE TITLE
Suggestion : ad-notimelt

### ISSUE THREAD

**Issue by jokerigno** [benleb/ad-notifreeze#1]
Hi,

just an idea: why don't you create the opposite component? An appdaemon that notifies you when outside temperature is higher than the one inside a room. I think it would be useful for spring or autumn. 

:)

**Comment by benleb** [comment]
this works already :) notifreeze checks the absolute difference of the temperature values. See
https://github.com/benleb/ad-notifreeze/blob/1af1e1ac7d696b6bb8842c87d5c6310f46c7f11d/apps/notifreeze/notifreeze.py#L85
& https://github.com/benleb/ad-notifreeze/blob/1af1e1ac7d696b6bb8842c87d5c6310f46c7f11d/apps/notifreeze/notifreeze.py#L123

**Comment by jokerigno** [comment]
Great! Thank you!
