### ISSUE TITLE
[feature request] localize

### ISSUE THREAD

**Issue by jokerigno** [benleb/ad-notifreeze#5]
Hi,

I would like to suggest to add the possibility to localize/personalize message on different languages-needs.

**Comment by jokerigno** [comment]
Up? 

There's a change to personalize the message in other languages?

**Comment by benleb** [comment]
sorry ✌️ I will investigate what has to be done to implement a simple localization system (which I also will implement in my other apps if its cool). depending on the effort needed, it may take a little time (up to end of November in worst case) as I am currently occupied by my thesis.

**Comment by benleb** [comment]
btw, you talk about messages that will be sent out as notifications right? I am pretty sure I won't like to localize log messages or even more...  😄

**Comment by benleb** [comment]
@jokerigno btw, you talk about messages that will be sent out as notifications right? I am pretty sure I won't like to localize log messages or even more... 😄

**Comment by jokerigno** [comment]
Yes just the message. I want to broadcast message to mi gminis when a window is open for a determined period so message should be on my native language and should be 'speakeable'. That's why I ask for localization and personalization :)

**Comment by benleb** [comment]
gminis? something like [gremlins](https://en.wikipedia.org/wiki/Gremlins)?

https://github.com/benleb/ad-notifreeze/blob/ea1ebb02488c61c87b5e5d1d8534102ed75aad6d/apps/notifreeze/notifreeze.py#L477 this should work?

**Comment by jokerigno** [comment]
LOL 

GMINIS are Google home mini (aka Google nest mini). I have 5 of them in all my house that send notifications based on some automation (washer finished, it's raining ecc). Your app will be a good implementation.

Related  to 477 yes it's definitely a good start. In my case I will add some " , " and translate also the arrow to make it speakble.

**Comment by jokerigno** [comment]
Hey I was thinking that the message could be more "speakable".

Something like This:

    "en_US": {
        "SINCE": "{room_name} {entity_name} open since {open_since}: {initial}°C",
        "CHANGE": "{room_name} {entity_name} open since {open_since}: {initial}°C → {indoor}°C ({indoor_difference}°C)",

    "en_US": {
        "SINCE": "{entity_name} in {room_name} is open since {open_since}. Temperature is still {initial}°C",
        "CHANGE": "{entity_name} in {room_name} is open since {open_since}. Temperature is changed from {initial}°C to {indoor}°C with this difference :({indoor_difference}°C)",

What do you think?

**Comment by jokerigno** [comment]
Was so bad as suggestment?

**Comment by benleb** [comment]
no, looks okay - but unfortunately, I had other things todo :P

But hey, check out https://github.com/benleb/ad-notifreeze#messages ;) Closing now as this is "solved"

**Comment by jokerigno** [comment]
Can you please add one example in the readme? I Tried withi this config but it doesn't work:

```
  message:
    since: "{entity_name} in {room_name} è aperta da {open_since}."
    change: "{entity_name} in {room_name} è aperta {open_since}: la temperatura è passata da {initial}°C a {indoor}°C con una differenza di ({indoor_difference}°C)."
```
2020-11-23 12:14:27.784901 WARNING notifreeze: ------------------------------------------------------------
2020-11-23 12:14:27.785120 WARNING notifreeze: Unexpected error running initialize() for notifreeze
2020-11-23 12:14:27.785266 WARNING notifreeze: ------------------------------------------------------------
2020-11-23 12:14:27.785533 WARNING notifreeze: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 148, in initialize_app
    await init()
  File "/config/appdaemon/apps/ad-notifreeze/notifreeze.py", line 176, in initialize
    if own_messages := self.args.pop("messages"):

**Comment by benleb** [comment]
ah sorry 😅 you are missing just the 's' of messages afaik :D 


this one is tested and works for me :)
```yaml
notifreeze:
  module: notifreeze
  class: NotiFreeze
  notify_service: notify.sybe
  always_notify: true
  outdoor: sensor.temperature_garden
  max_difference: 7.1
  delays: {initial: 6, reminder: 11}
  messages:
    since: "{room_name} {entity_name} open LOL {open_since}: {initial}°C"
  rooms:
    - schlafzimmer
    - bad
```

**Comment by jokerigno** [comment]
Oh god. Sorry for wasting your time!
