### ISSUE TITLE
[Feature request] list of notify_service

### ISSUE THREAD

**Issue by pniewiadowski** [benleb/ad-notifreeze#6]
Hi there,

thank you for this add on!

Will you be able to add feature to pull list of notify services from configuration
Now it seems to get only one?

**Comment by benleb** [comment]
use a [Notify Group](https://www.home-assistant.io/integrations/notify.group/) from home assistant :)

I think it makes more sense to do the grouping in home assistant. one advantage is that home assistant and NotiFreeze know of the group. another would be that you probably will use the same group for other things (in home assistant or other appdaemon apps) which is most convenient when centrally managed (by home assistant).

if you have good reason to do it another way, let me know, maybe I just never thought of :D
